version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000  

  backend:
    image: rajpandey55/courses_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=rajpandey55.settings  
      - DJANGO_ALLOWED_HOSTS=localhost
    volumes:
      - ./backend:/app  
